"""added image_path to answers and updated relationships

Revision ID: 339b317b8202
Revises: d503e4b32e76
Create Date: 2025-09-23 11:34:54.230340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339b317b8202'
down_revision = 'd503e4b32e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=100), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
